# Generated by Django 2.2.12 on 2020-06-01 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snipp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colabforms',
            name='description',
        ),
        migrations.RemoveField(
            model_name='colabforms',
            name='price',
        ),
    ]
