# Generated by Django 2.2.12 on 2020-06-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snipp', '0002_auto_20200601_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colabforms',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
