# Generated by Django 2.2.12 on 2020-06-02 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snipp', '0003_auto_20200601_2052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='colabForms',
            new_name='ModelEmail',
        ),
    ]
