# Generated by Django 2.2.12 on 2020-06-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snipp', '0005_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='assunto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
