# Generated by Django 2.2.12 on 2020-06-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snipp', '0006_auto_20200602_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelemail',
            name='numero',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
