# Generated by Django 2.2.12 on 2020-06-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snipp', '0006_auto_20200602_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('assunto', models.CharField(blank=True, max_length=200)),
                ('mensagem', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contato',
        ),
    ]
