# Generated by Django 2.2.12 on 2020-06-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snipp', '0008_auto_20200602_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='mensagem',
            field=models.TextField(blank=True),
        ),
    ]
