# Generated by Django 2.2.12 on 2020-06-03 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snipp', '0009_auto_20200602_1926'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contato',
        ),
    ]
